### ISSUE TITLE
Duplicate joke

### ISSUE THREAD

**Issue by Olson3R** [alexweininger/joke-api#1]
https://github.com/alexweininger/joke-api/blob/master/jokes/index.json#L211-L222

Appears to be a duplicate joke.

P.S. [This](https://github.com/alexweininger/joke-api/blob/master/jokes/index.json#L178) is my favorite so far.

**Comment by alexweininger** [comment]
Good catch!

I like that one too haha

**Comment by alexweininger** [comment]
OK - just removed the duplicate joke. 

Thank you again for taking the time to give some feedback.  Please feel free to add some of your jokes to the repo.  

- mac
